config/routes.rb
Jobtest::Application.routes.draw do
  get 'searches/index'
  get 'searches/show'
  get 'searches/find'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  resources :childmenus
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  root "home_pages#index"
	match "/admin", :to => "home_pages#admin", via: :get

	resources :mainmenus, only: [:create, :edit, :update, :destroy]

  match 'mainmenus/new/(:id)', to: 'mainmenus#new', as: :new_mainmenu, via: :get
  match 'mainmenus/:id', to: 'mainmenus#show', as: :show_mainmenu, via: :get

  resources :contents










end

app/models/mainmenu.rb
class Mainmenu < ActiveRecord::Base
=begin
	acts_as_tree order: 'created_at DESC'

	validates :title, presence: true, length: { maximum: 255 }
	validates :text, presence: true, length: { maximum: 500 }

	has_many :relationships, foreign_key: "parent_id", dependent: :destroy
	has_many :deriveds, through: :relationships, source: :derived

	has_many :reverse_relationships, foreign_key: "derived_id", class_name: "Relationship", dependent: :destroy
	has_many :parents, through: :reverse_relationships, source: :parent
=end
	has_many :childmenus, dependent: :destroy
	has_ancestry


	#def following?(other_user)
	#	relationships.find_by(followed_id: other_user.id)
	#end

	#def unfollow!(other_user)
	#	relationships.find_by(followed_id: other_user.id).destroy!
	#end
end

app/controllers/mainmenus_controller.rb
class MainmenusController < ApplicationController
	include ApplicationHelper
	before_action :get_mainmenus

  def index
		@mainmenus = Mainmenu.all
  end

  def show
	  @show_mainmenu = Mainmenu.find(params[:id])
  end

  def edit
	  @edit_mainmenu = Mainmenu.find(params[:id])
  end

	def update
		@update = Mainmenu.find(params[:id])
		if @update.update_attributes(params.require(:mainmenu).permit(:title, :text))
			redirect_to @update, notice: 'Mainmenu was successfully updated.'
		else
			render action: "edit"
		end
	end

  def new
	  @mainmenu = Mainmenu.new(:parent_id => params[:parent_id])
  end

  def create
		@create_mainmenu = Mainmenu.new(params.require(:mainmenu).permit(:parent_id, :title, :text))
		if !params.require(:mainmenu).permit(:parent_id).nil?
			@create_mainmenu.style_class = "nested_mainmenus site-dropdown-menu"
		else
			@create_mainmenu.style_class = "mmain"
		end
		if @create_mainmenu.save
			flash[:success] = 'Your children mainmenu was successfully added!'
			redirect_to @create_mainmenu
		else
			render 'new'
		end


  end

	def add

	end

  def destroy
	  @delete = Mainmenu.find(params[:id])
		if @delete.destroy
			flash[:success] = 'Mainmenu deleted'
			redirect_to root_path
		else
			flash[:success] = 'Delete error'
			render 'new'
		end
  end

	private

	def mainmenu_params
		params.require(:mainmenu).permit(:title, :text)
	end

	def get_mainmenus
		@mainmenu = Mainmenu.all
	end
end


#def deriveding?(other_page)
#	relationships.find_by(derived_id: other_page.id)
#end

#def adopt!(g_id, other_page)
#	rel = Relationship.new
#	rel.create!(parent_id: g_id, derived_id: other_page.id)
#end

#def unadopt!(other_page)
#	relationships.find_by(derived_id: other_page.id).destroy!
#end

app/helpers/mainmenus_helper.rb
module MainmenusHelper
	def nested_mainmenus(mm)
=begin
		mainmenus.map do |mainmenu, sub_mainmenus|
			mClass = "nested_mainmenus site-dropdown-menu"
			mId = "site-dropdown-menu-#{mainmenu.id}"
			mStyle = ""#"display: block;"
			render(mainmenu) + content_tag(:div, nested_mainmenus(sub_mainmenus), :class => "#{mClass}", :id => "#{mId}", :style => "#{mStyle}")
		end.join.html_safe
=end

    render "mainmenus/mainmenu", :mainmenus => mm
	end
end

app/views/mainmenus/_childmenus.html.erb
<% if mainmenu.childmenus.count > 0 %>
  <div class="childmenu-class">
    <%#= mainmenu.text %>
    <ul>
      <% mainmenu.childmenus.each do |cm| %>
        <li>
          <%= link_to cm.title, cm, class: "child-menu-title" %>
          <span class="links_separator"> | </span>
          <%= link_to "delete", cm, :method => :delete, class: "link-to-new-mainmenu" %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/mainmenus/_form.html.erb
<%= form_for @mainmenu do |f| %>

  <% @mainmenu.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
	<% end %>

  <%= f.hidden_field :parent_id, :value => @mainmenu.parent_id %>

	<div class="form-group">
	  <%= f.label :title, "title", class: "col-sm-3 control-label" %>
	  <%= f.text_field :title, class: "form-control" %>
	</div>


  <div class="form-group">
    <%= f.label :text, "New text", class: "col-sm-3 control-label" %>
    <%= f.text_area :text, :rows => 8, class: "form-control" %>
	</div>

  <div class="form-group">
	  <%= f.submit "Create", class: "btn btn-default" %>
  </div>

 <% end %>

app/views/mainmenus/_main_menu_tools.html.erb
<div class="main-menu-tools">
  <span class="mainmenu_created_at"><%= mainmenu.created_at.strftime("%m %d %Y") %></span>
  <%= link_to "Add mainmenu", new_mainmenu_path(:parent_id => mainmenu), class: "link-to-new-mainmenu" %>
  <span class="links_separator"> | </span>
  <%= link_to "Add childmenu", new_childmenu_path(:parent_id => mainmenu), class: "link-to-new-mainmenu" %>
  <span class="links_separator"> | </span>
  <%= link_to "Destroy", mainmenu, :confirm => "Are you sure?", :method => :delete, class: "link-to-new-mainmenu" %>
</div>

app/views/mainmenus/_mainmenu.html.erb
<% mainmenus.map do |mainmenu, sub_mainmenus| %>

  <div id="main-title-<%= mainmenu.id %>" class="<%= mainmenu.style_class %>">
    <span class="main-title" onclick=""><%= mainmenu.title %></span>
		<%= render "mainmenus/main_menu_tools", :mainmenu => mainmenu %>
	  <%= render "mainmenus/childmenus", :mainmenu => mainmenu %>
    <%= nested_mainmenus(sub_mainmenus) %>
  </div>

<% end %>

app/views/mainmenus/_menu.html.slim
h1 Mainmenus#index
p Find me in app/views/mainmenus/_index.html.haml

p
  = link_to "add first mainmenu", new_mainmenu_path, :class => "link-to-new-mainmenu"

=# nested_mainmenus @mainmenus.arrange(:order => :created_at)

app/views/mainmenus/add.html.slim
.info
  h4
    | Pages#new
    | Find me in app/views/pages/new.html.slim

= form_for @new_page do |form|
	- if !@g.nil?
		= form.hidden_field :g, name: :gen_info, value: @g
	= form.text_field :title
	br
	= form.text_area :text, :class => "textarea"
	br

	= form.submit "create page"

app/views/mainmenus/destroy.html.erb
<h1>Pages#destroy</h1>
<p>Find me in app/views/pages/destroy.html.erb</p>

app/views/mainmenus/edit.html.erb
<div class="info">
  <h4>Pages#edit</h4>
  Find me in app/views/pages/edit.html.erb
</div>

<%= form_for @edit_mainmenu do |f| %>
  <%= f.text_field :title, :value => @edit_mainmenu.title %><br/>
  <%= f.text_area :text, :value => @edit_mainmenu.text, :class => "textarea" %><br/>
  <%= f.submit "update" %>
<% end %>

app/views/mainmenus/new.html - копия.slim
.info  h4    | Pages#new    | Find me in app/views/pages/new.html.erb= form_for @page do |form|  = form.hidden_field :parent_id  = form.text_field :title  br  = form.text_area :text, :class => "textarea"  br  = form.submit "create page"

app/views/mainmenus/new.slim
h5
  |Pages with render page

/= render @mainmenu.parent if @mainmenu.parent
= render "form"

app/views/mainmenus/show.html.slim
.info
  h4
    | Mainmenus#show
	| Find me in app/views/mainmenus/show.html.haml


- flash.each do |name, msg|
  = content_tag :div, msg, class: "alert alert-info"


h4
  = @show_mainmenu.title

= @show_mainmenu.text.html_safe
br
= link_to "Edit", edit_mainmenu_path
= " | "
= link_to "Add mainmenu", new_mainmenu_path(:parent_id => @show_mainmenu)