config/routes.rb
Jobtest::Application.routes.draw do
  get 'searches/index'
  get 'searches/show'
  get 'searches/find'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  resources :childmenus
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  root "home_pages#index"
	match "/admin", :to => "home_pages#admin", via: :get

	resources :mainmenus, only: [:create, :edit, :update, :destroy]

  match 'mainmenus/new/(:id)', to: 'mainmenus#new', as: :new_mainmenu, via: :get
  match 'mainmenus/:id', to: 'mainmenus#show', as: :show_mainmenu, via: :get

  resources :contents










end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    per_page = 15
	  if !params[:users].nil?
		  from = params[:users][:from]
		  to   = params[:users][:to]

		  p = []

		  from.each do |f|
			  if !f[1].empty?
				  #ниже делается строка запроса для выборки по диапозону или с простым условием
				  #to[f[0]].empty? ? p.push("#{f[0]} = #{f[1]}") : to[f[0]] >= f[1] ? p.push("#{f[0]} BETWEEN #{f[1]} and #{to[f[0]]}") : "no"

          if to[f[0]].empty?
	          p.push("#{f[0]} = #{f[1]}")
          else
						if to[f[0]] >= f[1]
							p.push("#{f[0]} BETWEEN #{f[1]} and #{to[f[0]]}")
						else
							"no"
						end
          end

			  end
		  end

		  p = p.join(" AND ")

      @users = User.where(p).order("age desc").paginate(page: params[:page], :per_page => per_page)
	  else
		  @users = User.paginate(page: params[:page], :per_page => per_page)
	  end
  end

  def find
		respond_to do |format|
			format.html
			format.js
		end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

=begin
	def following?(other_page)
		relationships.find_by(followed_id: other_page.id)
	end

	def follow!(other_page)
	  relationships.create!(followed_id: other_page.id)
	end

	def unfollow!(other_page)
		relationships.find_by(followed_id: other_page.id).destroy!
	end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:age, :pay, :stature, :weigh)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :pay %><br>
    <%= f.number_field :pay %>
  </div>
  <div class="field">
    <%= f.label :stature %><br>
    <%= f.number_field :stature %>
  </div>
  <div class="field">
    <%= f.label :weigh %><br>
    <%= f.number_field :weigh %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/find.slim
= form_for("users", url: users_path, method: :get, :html => {style:"width:490px"}) do |f|
	= f.fields_for "from" do |from|
		div style="width:245px; float:left;"

			div class="find-field"
				div class="find-cell"age
				div class="find-cell"= from.text_field :age

			div class="find-field"
				div class="find-cell"pay
				div class="find-cell"= from.text_field :pay

			div class="find-field"
				div class="find-cell"stature
				div class="find-cell"= from.text_field :stature

			div class="find-field"
				div class="find-cell"weigh
				div class="find-cell"= from.text_field :weigh

	= f.fields_for "to" do |to|
		div style="width:245px; float:left;"

			div class="find-field"
				div class="find-cell"to age
				div class="find-cell" = to.text_field :age

			div class="find-field"
				div class="find-cell"to pay
				div class="find-cell" = to.text_field :pay

			div class="find-field"
				div class="find-cell"to stature
				div class="find-cell" = to.text_field :stature

			div class="find-field"
				div class="find-cell"to weigh
				div class="find-cell" = to.text_field :weigh

	div
		= f.submit "find"

app/views/users/index.html.erb
<h4>Listing users</h4>
<p>
  <%#= link_to 'Selection', searches_index_path %>
</p>


<% flash.each do |name, msg| %>
  <%= msg %><br/>
<% end %>

<div class="container">
  <%= will_paginate @users, :previous_label => " « ", :next_label => " » ", inner_window: 1, outer_window: 1 %>
</div>

<div class="container">
  <table style="border-left: 1px solid #b2b2b2; border-top: 1px solid #b2b2b2;" class="users-table">
    <thead>
    <tr>
      <th>Age</th>
      <th>Pay</th>
      <th>Stature</th>
      <th>Weigh</th>
      <th>Email</th>
      <th colspan="3">actions</th>
    </tr>
    </thead>



    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.age %></td>
        <td><%= user.pay %></td>
        <td><%= user.stature %></td>
        <td><%= user.weigh %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>


<div class="container">
	<%= will_paginate @users, :previous_label => " « ", :next_label => " » ", inner_window: 1, outer_window: 1  %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Pay:</strong>
  <%= @user.pay %>
</p>

<p>
  <strong>Stature:</strong>
  <%= @user.stature %>
</p>

<p>
  <strong>Weigh:</strong>
  <%= @user.weigh %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>