config/routes.rb
Jobtest::Application.routes.draw do
  get 'searches/index'
  get 'searches/show'
  get 'searches/find'

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  resources :childmenus
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  root "home_pages#index"
	match "/admin", :to => "home_pages#admin", via: :get

	resources :mainmenus, only: [:create, :edit, :update, :destroy]

  match 'mainmenus/new/(:id)', to: 'mainmenus#new', as: :new_mainmenu, via: :get
  match 'mainmenus/:id', to: 'mainmenus#show', as: :show_mainmenu, via: :get

  resources :contents










end

app/models/childmenu.rb
class Childmenu < ActiveRecord::Base
	has_many :contents, dependent: :destroy
	belongs_to :mainmenu
end

app/controllers/childmenus_controller.rb
class ChildmenusController < ApplicationController
  def show
    @childmenu = Childmenu.find(params[:id])
  end

  def new
    @childmenu = Childmenu.new(:mainmenu_id => params[:parent_id])
  end

  def create
    @childmenu = Childmenu.new(params.require(:childmenu).permit(:mainmenu_id, :title, :text))
    if @childmenu.save
      redirect_to @childmenu, notice: 'Childmenu was successfully updated.'
    else
      flash[:error] = 'Delete Childmenu error'
      render action: "new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @delete = Childmenu.find(params[:id])
    if @delete.destroy
      redirect_to root_path#new_childmenus_path, notice: 'Childmenu was successfully deleted.'
    else
      flash[:success] = 'Delete Childmenu error'
      render 'new'
    end
  end
end

app/helpers/childmenus_helper.rb
module ChildmenusHelper
end

app/views/childmenus/_form.html.erb
<%= form_for @childmenu do |f| %>

	<% @childmenu.errors.full_messages.each do |msg| %>
		<p><%= msg %></p>
	<% end %>

  <%= f.hidden_field :mainmenu_id, :value => @childmenu.mainmenu_id %>

	<div class="form-group">
		<%= f.label :title, "title", class: "col-sm-3 control-label" %>
		<%= f.text_field :title, class: "form-control" %>
	</div>


  <div class="form-group">
    <%= f.label :text, "New text", class: "col-sm-3 control-label" %>
    <%= f.text_area :text, :rows => 8, class: "form-control" %>
	</div>

  <div class="form-group">
    <%= f.submit "Create", class: "btn btn-default" %>
  </div>

<% end %>

app/views/childmenus/create.html.slim
h1 Childmenus#create
p Find me in app/views/childmenus/create.html.haml

app/views/childmenus/desrtoy.html.slim
h1 Childmenus#desrtoy
p Find me in app/views/childmenus/desrtoy.html.haml

app/views/childmenus/edit.html.slim
h1 Childmenus#edit
p Find me in app/views/childmenus/edit.html.haml

app/views/childmenus/new.html.slim
h1 Childmenus#new
p Find me in app/views/childmenus/new.html.haml

= render "form"

app/views/childmenus/show.html.slim
h1 Childmenus#show
p Find me in app/views/childmenus/show.html.haml



h5
  = @childmenu.title
= @childmenu.text
p
  = link_to "Add post", new_content_path(:childmenu_id => @childmenu)
  span.links_separator= " | "
  = link_to "Edit", edit_childmenu_path(@childmenu)
  span.links_separator= " | "
  = link_to "Destroy", childmenu_path(@childmenu), confirm: "Are you sure?", method: :delete

h4
  | Posts

- @childmenu.contents.each do |content|
  h5
    = content.title
  = content.text.html_safe
  p
    = link_to "Open post", content_path(content)
    span.links_separator= " | "
    = link_to "Edit post", edit_content_path(content)
    span.links_separator= " | "
    = link_to "Destroy", content_path(content), confirm: "Are you sure?", method: :delete

app/views/childmenus/update.html.slim
h1 Childmenus#update
p Find me in app/views/childmenus/update.html.haml